version: '3.5'
services:
  redis:
    image: "redis:alpine"
  bot:    
    image: mathewjpallan/rasachatbot:0.0.1
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "5005:5005"
    environment:
      - TMP=TMP
  router:    
    image: mathewjpallan/rasachatrouter:0.0.1
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "4000:4000"
      - "8443:8443"
    environment:
      - RASA_CORE_ENDPOINT=http://bot:5005/webhooks/rest/webhook
      - REDIS_HOST=redis
      - HTTPS_PATH_KEY=/run/secrets/site.key
      - HTTPS_PATH_CERT=/run/secrets/site.crt
      - HTTPS_PATH_CA=/run/secrets/site.ca
    secrets:
      - site.key
      - site.crt
      - site.ca
secrets:
   site.key:
     file: /home/mathew/Desktop/tmp/site.key
   site.crt:
     file: /home/mathew/Desktop/tmp/site.crt
   site.ca:
     file: /home/mathew/Desktop/tmp/site.ca     